layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-tidy
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects: p7zip

social_media:
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: ostaniriccardo
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: rikyoz92
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: C++
    web_url: https://github.com/topics/cplusplus
    image_url: https://cdn.jsdelivr.net/gh/gilbarbara/logos@2.0/logos/c++.svg

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://cdn.jsdelivr.net/gh/gilbarbara/logos@2.0/logos/python.svg

  - name: Cyber Security
    web_url: https://github.com/topics/security
    image_url: https://cdnjs.cloudflare.com/ajax/libs/octicons/8.5.0/svg/shield.svg
