layout: stacked
style: light
title: Riccardo Ostani &#8211; Software Developer
description: A software developer focused on cybersecurity, good design practices, and clean code principles.
keywords: Riccardo, Ostani, software, developer, graduated, engineering, computer, science, master's degree, fast learner, highly motivated, hard-working, hard working, cybersecurity, cyber, security, software development, programming, coding, secure coding, clean coding, bit7z, QtCryptoHash, MrHash, APTScout, C++, Java, Python
author: Riccardo Ostani
job: Software Developer
url: "https://rikyoz.github.io/"

plugins:
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-sitemap
  - jekyll-tidy
  - jemoji

permalink: /:year/:month/:day/:title/

sass:
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects: p7zip

social_media:
  linkedin: ostaniriccardo
  twitter: rikyoz92
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # website: http://your_website_url
  # youtube: your_username

skills:
  languages:
    - C++
    - Java
    - Python
    - C
    - HTML5
    - CSS3
    - XML
    - JSON
    - JavaScript
    - PHP
    - SQL

  frameworks & tools:
    - Git
    - GitHub
    - Qt
    - QtCreator
    - Visual Studio
    - Android Studio
    - IntelliJ Idea
    - CLion
    - VirtualBox
    - Photoshop

  platforms:
    - Windows
    - Linux
    - Android

education:
  - type: Bachelor's Degree
    title: Ingegneria Informatica e Automatica
    thesis: "Catch: progettazione e realizzazione dell'applicazione Android"
    where: Università degli Studi di Roma &ldquo;La Sapienza&rdquo;
    language: Italian
    mark: 110
    date: March 30, 2016
    octicon: mortar-board

  - type: Master's Degree
    title: Engineering in Computer Science
    thesis: "APTScout: Windows API Usage for APT Malware Analysis"
    where: Università degli Studi di Roma &ldquo;La Sapienza&rdquo;
    language: English
    mark: 110 (with honors)
    date: January 20, 2020
    octicon: mortar-board

# topics:
#   - name: Cyber Security
#     web_url: https://github.com/topics/security
#     image_url: https://cdnjs.cloudflare.com/ajax/libs/octicons/8.5.0/svg/shield.svg

#   - name: Software Development
#     web_url: https://github.com/topics/development
#     image_url: https://cdnjs.cloudflare.com/ajax/libs/octicons/8.5.0/svg/code.svg

#   - name: C++
#     web_url: https://github.com/topics/cplusplus
#     image_url: https://cdn.jsdelivr.net/gh/gilbarbara/logos@2.0/logos/c++.svg

#   - name: Python
#     web_url: https://github.com/topics/python
#     image_url: https://cdn.jsdelivr.net/gh/gilbarbara/logos@2.0/logos/python.svg