name: "main"
on:
  push:
  pull_request:
    types: [opened, synchronize, skip ci]
  schedule:
    # Every day
    - cron:  '0 10 */1 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild GitHub Pages
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
            curl -L -X POST -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pages/builds"
